### ISSUE TITLE
Deep links to pages in other languages: page_for_app_request throws exception

### ISSUE THREAD

**Issue by tecjam** [matthiask/feincms3#20]
When implementing language deep links using the documentation, `page = page_for_app_request(request, Page.objects.active())` throws an exception

`page_for_app_request() takes 1 positional argument but 2 were given`

It should be 

`page_for_app_request(request, queryset=Page.objects.active())`

Changing the previous code throws another exception:

```
Traceback (most recent call last):
  File "/app/lib/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/app/lib/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/lib/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/app/pages/views.py", line 11, in page_detail
    page_for_app_request(request, queryset=Page.objects.active())
  File "/app/lib/feincms3/applications.py", line 264, in page_for_app_request
    app_instance_namespace=request.resolver_match.namespaces[1],
IndexError: list index out of range
```

**Comment by matthiask** [comment]
@tecjam Thanks for the report! The example was bad, the code too.

Reading your report again, it seems there's something else going on though. `page_for_app_request` shouldn't be used when rendering pages, it should only be used within feincms3 applications (https://feincms3.readthedocs.io/en/latest/guides/apps-introduction.html)

**Comment by matthiask** [comment]
https://feincms3.readthedocs.io/en/latest/build-your-cms.html#views-and-urls <- here's an example for a `page_detail` function, without `page_for_app_request`
