### ISSUE TITLE
Why multisite?

### ISSUE THREAD

**Issue by guettli** [matthiask/feincms3#21]
I like the philosophy behind FeinCMS3.

Why did you implement [multisite support](https://feincms3.readthedocs.io/en/latest/guides/multisite.html)?

**Comment by matthiask** [comment]
It often happens that we have the same site running on different domains, one domain per language. In this case we want one admin interface, one supporters list (e.g. for a petition or political campaign), but one page tree per site.

One example for this is https://www.agrarlobby-stoppen.ch/ and https://www.stop-agrobusiness.ch/ . Maybe there are some SEO-related downsides to this but it's important for national political campaigns in Switzerland to offer a first-class experience to all national languages (I hope this doesn't sound pompous.)

**Comment by matthiask** [comment]
Another point: feincms3-sites replaces running WSGI instances per language by one additional database query per language. The additional query could be avoided by caching the list of sites somehow.

**Comment by guettli** [comment]
This makes sense.Thank you for your answer.
