### ISSUE TITLE
Moving pages doesn’t work

### ISSUE THREAD

**Issue by fiee** [matthiask/feincms3#23]
In 0.41 (didn’t check other versions), moving a page in the Admin doesn’t work – MoveForm shows up and there’s a success message on submit, but the page is never moved.

**Comment by matthiask** [comment]
Hmm that's really strange. I double- and triple-checked this just now and it works for me.

Are you subclassing `feincms3.pages.AbstractPage` and using the default `TreeAdmin` implementation? 

I see that `MoveForm` isn't as generic as it sounds because it assumes that nodes are ordered by a `position` integer field, but that is the case for the `AbstractPage`.

**Comment by fiee** [comment]
A happy and healthy new year BTW!

> Are you subclassing `feincms3.pages.AbstractPage` and using the default `TreeAdmin` implementation?

Yes and yes.

It’s the same with "runserver" on my Mac (Python 3.8.2) and with gunicorn on my Debian server (Python 3.7.9), both with Django 2.2.17 and feincms3 0.41 (and some of your other apps).

**Comment by fiee** [comment]
Sorry, better error description:
I can move single pages or whole hierarchies in and out of hierarchies, but I can’t re-order pages or subtrees, i.e. change the position of a subtree or a page within the same subtree.

Did I miss some ordering configuration?

**Comment by matthiask** [comment]
Ah hmm... maybe you are redefining `class Meta` inside `class Page`? You'll have to redefine `ordering = ["position"]`

**Comment by fiee** [comment]
I didn’t define `Meta`, but defining it with the ordering property fixed the issue.

Thank you very much!

**Comment by matthiask** [comment]
Great!

I have added a system check to hopefully prevent this error from resurfacing in the future: https://github.com/matthiask/feincms3/commit/174d14aa10d1838033b613778a95369ace6b03e1

**Comment by gradel** [comment]
Having AbstractPage in the first position in the List of base classes prevents this error. Otherwise the Meta class of AbstractPage gets lost. You may also explicitly inherit AbstractPages's Meta class in your Page definition.

**Comment by matthiask** [comment]
Oh wow, that's an excellent point. I noticed that all of our code has `AbstractPage` in the first place, as does https://github.com/matthiask/feincms3-example

I updated the docs (and the CHANGELOG) to be a better guide in this matter. Thanks!! https://github.com/matthiask/feincms3/commit/393a1466095d0f3e74b6bc2342ae51a3459f60a6
