### ISSUE TITLE
Examples for generating navigation (was: Usage of menus)

### ISSUE THREAD

**Issue by serdargkaya** [matthiask/feincms3#6]
Hi @matthiask
Could you help with menus. I couldn't figure out how to use "group_by_tree" filter.

`             
{% menus as menus %}
              {% for p in menus.ana|group_by_tree %}
              <li>
                <a class="nav-link" href="{{ p.get_absolute_url }}">{{ p.title }}</a>
                <ul>
                  {% for i in p %}
                  <li><a href="">{{ i }}</a></li>
                  {% endfor %}
                </ul>
              </li>
{% endfor %}
`

**Comment by matthiask** [comment]
There's an example here:
https://github.com/matthiask/feincms3/blob/0.14/feincms3/templatetags/feincms3_pages.py#L13

You should write something like `{% for parent, children in menus.ana|group_by_tree %}`, and then do something with the parent node and iterate over the children nodes (`{% for p in children %}...`)

Does that help?

**Comment by kayadata** [comment]
Thanks matt it did help.

**Comment by matthiask** [comment]
Great!

**Comment by kayadata** [comment]
hi me again with new question :) i think we need more doc about navs. Im actively using this cms for my clients. 

1. Need a templatetag for breadcrumb
2. How we query in template only current page's children

**Comment by meshy** [comment]
I don't know if this is useful, but the `feincms-extensions` package has [a nice template](https://github.com/incuna/feincms-extensions/blob/63f9d67943ac6a1f749dea070e6813a0792ace8c/feincms_extensions/templates/feincms_extensions/navigation.html) that I generally use as a guideline for making navs.

**Comment by matthiask** [comment]
Breadcrumbs:

```
<nav class="breadcrumbs">
{% for p in page.get_ancestors %}
    <a href="{{ p.get_absolute_url}}">{{ p }}</a> &rsaquo;
{% endfor %}
    <span>{{ page }}</span>
</nav>
```

Only direct children:

```
<nav class="children">
    {% for p in page.children.active %}
        {# Do something with p #}
    {% endfor %}
</nav>
```

feincms3 does not bundle any code to do this because it's really straightforward and everything can be achieved directly inside templates, no template tags necessary. I'm not opposed to adding examples to he documentation though, do you want to throw something together? (Don't worry if it's not polished. I'm no native english speaker either, but will happily edit it. Getting the first draft is the hard thing.)

**Comment by matthiask** [comment]
Thanks @meshy that looks great as well. The template depends on django-mptt though, django-cte-forest does not have tags such as `{% recursetree %}` right now.

**Comment by meshy** [comment]
Oops! You're quite right! I forgot I was looking at the _feincms3_ repo instead of just feincms, sorry!

**Comment by matthiask** [comment]
Yeah, happens to me all the time :-) the incompatibility bothers me, but I don't really know what to do about it (yet?)

**Comment by kayadata** [comment]
Thanks guys. i didn't think to look at django-cte-forest's source code. my bad :)
And yeap its really simple. Don't have enough time but sure i will help write the docs later.

https://github.com/matthiask/django-cte-forest/blob/master/cte_forest/models.py#L1063

Breadcrumb:
```
<ol class="breadcrumb">
      {% for p in page.ancestors %}
      <li class="breadcrumb-item"><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></li>
      {% endfor %}
      <li class="breadcrumb-item active">{{ page.title }}</li>
</ol>
```

**Comment by matthiask** [comment]
Reopening as a documentation issue.
