### ISSUE TITLE
Best way to query for different page's region at template

### ISSUE THREAD

**Issue by serdargkaya** [matthiask/feincms3#7]
Like how to we query, say about page's main region at homepage's template.

**Comment by matthiask** [comment]
What you'd probably want in this case is make the current page a descendant of the home page, use the same key for regions (for example `sidebar` or something), and mark the region as `inherited`. 

`Contents.inherit_regions` will do the rest for you (https://github.com/matthiask/django-content-editor/blob/master/content_editor/contents.py#L54)

Respectively, `content_editor.contents.contents_for_item(page, plugins, inherit_from=<queryset containing ancestors>`, that is (when using django-cte-forest) `contents_for_item(page, plugins, inherit_from=page.ancestors().reverse())`

feincms3's `TemplatePluginRenderer` also supports `inherit_from`, so what you'd probably want to do in this case is this: https://github.com/matthiask/feincms3/blob/master/feincms3/renderer.py#L32

---

If you want to go low level, something like this would also work:

```
renderer = ... # your TemplatePluginRenderer instance
home = ... # some way to get the home page instance

contents = contents_for_item(home, renderer.plugins())

# Example:
main_region_contents = contents.main  # or contents['main'] -- does the same thing
```

**Comment by kayadata** [comment]
Im trying to get items with a simple tag.
```
from content_editor.contents import Contents
@register.simple_tag
def show_headline(split):
    headlines = Page.objects.filter(headline=True)[:split]
    for i in headlines:
        content = Contents(i.regions)
        for item in i.pages_richtext_set.all():
            content.add(item)
        for item in i.pages_image_set.all():
            content.add(item)
    return headlines
```
And in template im trying to query like this

```
        {% show_headline 5 as headline %}
        {% for item in headline %}
        <div class="slide">
          <div class="row">

            <div class="col-md-6">
              <div class="headline">
                <h1>{{ item.title }}</h1>
                {{ content.description }}
                <a href="{{ item.get_absolute_url }}" class=" btn btn-primary">Go to Product</a>
              </div>
            </div>
            <div class="col-md-6">
              <div class="product-photo">
                {{ content.image }}
              </div>
            </div>

          </div>
        </div>
        {% endfor %}
```

and no luck so far. I think im making stupid mistake again :-1:

**Comment by matthiask** [comment]
Well, you're not returning the contents objects at all!

I'd do something like this (untested):

```
from collections import OrderedDict

@register.simple_tag
def show_headline(split):
    pages = Page.objects.filter(headline=True)[:split]
    contents = {page: Contents(page.regions) for page in pages}
    for item in page.pages_richtext_set.all():
        contents[item.parent].add(item)
    for item in page.pages_image_set.all():
        contents[item.parent].add(item)
    return contents.items()
```

... and in the template, use `{% for page, contents in headline %}`

**Comment by matthiask** [comment]
Respectively, much shorter:

```
from content_editor.contents import contents_for_items

pages = Page.objects.filter(headline=True)[:split]
contents = contents_for_items(pages, plugins=[RichText, Image])
return [(page, contents[page]) for page in pages]
```

(See http://django-content-editor.readthedocs.io/en/latest/#contents-for-items)

**Comment by kayadata** [comment]
Thanks @matthiask . Its much simple. Btw if u don't want me to ask this kind of questions. I won't.
But this feature is fundemantal for every business company website or such.
And be sure i will write docs for everything that i've asked for.

**Comment by matthiask** [comment]
You're welcome, and don't worry: It's good to hear that the software is being used. Also, developer questions are often documentation bugs, so please don't hesitate to ask more!

**Comment by matthiask** [comment]
I'm not completely sure what to write here now, especially since the TemplatePluginRenderer and its Regions class made everything so much more flexible. Maybe https://feincms3.readthedocs.io/en/latest/rendering.html is sufficient now? Or maybe it would make sense to explain all the layers that are involved in rendering feincms3 sites these days?

**Comment by serdargkaya** [comment]
We should just refer to django-content-editor's docs in rendering.html for more examples. I think that's enough. If you agree we can close this issue.

**Comment by serdargkaya** [comment]
Soo just read the docs again. And no need for what i asked. With this doc
https://feincms3.readthedocs.io/en/latest/renderer.html we can close this issue.

**Comment by matthiask** [comment]
Great! Thanks. Documentation still needs work, work in progress towards an 1.0 release is here: https://feincms3.readthedocs.io/en/v1-docs/
